#!/usr/bin/python3

from sympy import factorint
import sys

def factorize_file(file_path):
    """
    This function reads a file of integers line by line and factorizes each of them.

    Parameters:
    file_path (str): the path to the file containing the integers.

    Returns:
    None

    """
    with open(file_path, 'r') as file:
        for line in file:
            n = int(line.strip())
            factors = factorint(n)
            for p, exp in factors.items():
                print(f"{n}={p}*{n//p}")
                break

if __name__ == "__main__":
    factorize_file(sys.argv[1])